apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: parallel-sharding-cb

on:
  workflow_dispatch:
    

jobs:
  job1:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "job1"
  job2:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "job2"
  final_job:
    needs: [job1, job2]
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "final job"
