apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: parallel-sharding-cb

on:
  workflow_dispatch:
    

jobs:
  job1:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "job1"
          mkdir -p job-output
          echo "job1" >> ./job-output/job1.txt
          tree -L 2
          echo $(pwd)/job-output >> "$CLOUDBEES_OUTPUTS/job1"
  job2:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "job2"
          mkdir -p job-output
          echo "job2" >> ./job-output/job2.txt
          tree -L 2
          echo $(pwd)/job-output >> "$CLOUDBEES_OUTPUTS/job2"
  final_job:
    needs: [job1, job2]
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "final job"
          ls ${{needs.job1.outputs.output1}}
          ls ${{needs.job2.outputs.output1}}
