name: Start CB workflow from GHA
on:
    workflow_dispatch: 

permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

jobs:
    test:
        runs-on: ubuntu-22.04   
        steps:
          - name: Run CloudBees Workflow
            uses: cloudbees-gha-cbp/run-cloudbees-workflow@main
            id: go-action
            with:
              cloudbees-pat: ${{ secrets.CBP_PAT_GHA }}
              workflow-file-name: "my-workflow.yaml"
              cloudbees-url: "https://api.saas-qa.beescloud.com"

          - name: Use runUrl output
            run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"